export const labels = [
  { id: 0, name: "No Label", value: null },
  { id: 1, name: "Accessories", value: "accessories" },
  { id: 2, name: "Activewear", value: "activewear" },
  { id: 3, name: "Athletic Shoes", value: "athletic_shoes" },
  { id: 4, name: "Automotive", value: "automotive" },
  { id: 5, name: "Baking Supplies", value: "baking_supplies" },
  { id: 6, name: "Bath & Body", value: "bath_body" },
  { id: 7, name: "Beachwear", value: "beachwear" },
  { id: 8, name: "Beverages", value: "beverages" },
  { id: 9, name: "Books", value: "books" },
  { id: 10, name: "Boots", value: "boots" },
  { id: 11, name: "Camping Gear", value: "camping_gear" },
  { id: 12, name: "Casual Wear", value: "casual_wear" },
  { id: 13, name: "Canned Goods", value: "canned_goods" },
  { id: 14, name: "Cereals", value: "cereals" },
  { id: 15, name: "Clothing", value: "clothing" },
  { id: 16, name: "Collectibles", value: "collectibles" },
  { id: 17, name: "Computers", value: "computers" },
  { id: 18, name: "Craft Beverages", value: "craft_beverages" },
  { id: 19, name: "Craft Supplies", value: "craft_supplies" },
  { id: 20, name: "Dairy Products", value: "dairy_products" },
  { id: 21, name: "DIY Kits", value: "diy_kits" },
  { id: 22, name: "Electronics", value: "electronics" },
  { id: 23, name: "Fitness Trackers", value: "fitness_trackers" },
  { id: 24, name: "Food & Drink", value: "food_drink" },
  { id: 25, name: "Fragrances", value: "fragrances" },
  { id: 26, name: "Frozen Foods", value: "frozen_foods" },
  { id: 27, name: "Fruits", value: "fruits" },
  { id: 28, name: "Gaming Consoles", value: "gaming_consoles" },
  { id: 29, name: "Gadgets", value: "gadgets" },
  { id: 30, name: "Garden Tools", value: "gardening_tools" },
  { id: 31, name: "Health Supplements", value: "health_supplements" },
  { id: 32, name: "Heels", value: "heels" },
  { id: 33, name: "Home Appliances", value: "home_appliances" },
  { id: 34, name: "Home Decor", value: "home_decor" },
  { id: 35, name: "Home Fit-Outs", value: "home_fit_outs" },
  { id: 36, name: "Jewelry", value: "jewelry" },
  { id: 37, name: "Kitchenware", value: "kitchenware" },
  { id: 38, name: "Luggage", value: "luggage" },
  { id: 39, name: "Limited Edition Items", value: "limited_edition_items" },
  { id: 40, name: "Local Artisans", value: "local_artisans" },
  { id: 41, name: "Makeup", value: "makeup" },
  { id: 42, name: "Meat", value: "meat" },
  { id: 43, name: "Nuts & Seeds", value: "nuts_seeds" },
  { id: 44, name: "Office Supplies", value: "office_supplies" },
  { id: 45, name: "Oral Care", value: "oral_care" },
  { id: 46, name: "Outdoor Gear", value: "outdoor_gear" },
  { id: 47, name: "Personal Care", value: "personal_care" },
  { id: 48, name: "Pet Supplies", value: "pet_supplies" },
  { id: 49, name: "Phone Accessories", value: "phone_accessories" },
  { id: 50, name: "Refined Oils", value: "refined_oils" },
  { id: 51, name: "Seasonal Goods", value: "seasonal_goods" },
  { id: 52, name: "Skin Care", value: "skin_care" },
  { id: 53, name: "Snacks", value: "snacks" },
  { id: 54, name: "Sunglasses", value: "sunglasses" },
  { id: 55, name: "Subscription Boxes", value: "subscription_boxes" },
  { id: 56, name: "Sustainable Products", value: "sustainable_products" },
  { id: 57, name: "Tablets", value: "tablets" },
  { id: 58, name: "Travel Accessories", value: "travel_accessories" },
  { id: 59, name: "Travel Guides", value: "travel_guides" },
  { id: 60, name: "Toys", value: "toys" },
  { id: 61, name: "Vintage Clothing", value: "vintage_clothing" },
  { id: 62, name: "Vintage Items", value: "vintage_items" },
  { id: 63, name: "Workwear", value: "workwear" },
  { id: 64, name: "Winter Gear", value: "winter_gear" }
]